### ISSUE TITLE
Compatibility with extended bindings

### ISSUE THREAD

**Issue by LastElf** [brianmhunt/knockout-secure-binding#41] opened 2015-05-21 12:55 UTC
Hi Brian

Firstly, forgive me for any badly worded explanations. I've only been coding for a year and this is the first time I've tried to fix a problem involving multiple libraries.

Long story short, I'm converting my web game (http://town.compuception.com.au) to a packaged app to take advantage of the chrome.storage functionality. My code is heavily written with Knockout and Bootstrap to handle the UI for me (Cause lazy) and I'm using a plugin (https://github.com/faulknercs/Knockstrap) that handles templating modal boxes with KO bindings.

I've set up KSB using your guide and all the standard bindings work, however the template falls apart and crashes with an `Uncaught #<Object>` error that goes back to the ko.applyBindings() line where I build the content of the tabbed page. This stops when it's loading the first modal. So it appears that the template itself works (It loads the static data as seen here http://i.imgur.com/ro3Hcpa.jpg), however it can't pass $data to the template to flesh out the rest of it (Should look like this http://i.imgur.com/Fj6x69l.jpg)?

I understand if this isn't the fault of your code, but I was curious to know if you could explain how KSB handles other KO extended bindings and if there's a way that I can still use templates like this inside of a packaged app? The way I understood it was that your binding handler takes over and handles all of the default functionality that any extends would try and use?

**Comment by brianmhunt** [comment] 2015-05-21 15:58
Thanks for the report, @LastElf –– is there any chance you could put together a jsFiddle (or jsBin) that reproduces the problem? That would certainly make it easier for me to root out the issue.

Cheers :beers:

**Comment by brianmhunt** [comment] 2015-05-21 15:59
Incidentally – what happens when you run KSB on the web game web-page? Do you get the issue there? Or only in an app?

**Comment by LastElf** [comment] 2015-05-22 03:59
Ok, after two hours of throwing code at the jsbin I think I've figured out the cause. I use `click: function(){otherFunction(variable)}` in my code to pass variables to the click function, changing worker counts or bulk equipment value. Up until I added in the function inside the binding it was working perfectly find, so it appears to be that causing the problem.

http://jsbin.com/potojamoxe/1/

This works as intended with `ko.bindingProvider.instance = new ko.secureBindingsProvider(KSBoptions);` commented out so I think it's related to KSB getting in the way of completing an inline function? Is this a side effect of CSP and not being able to run eval code in a packaged app that you were trying to work around? I thought being able to run expressions inside the bindings as normal but after re-reading your docco it seems function() isn't allowed?

Would it be better practice to put all those inline functions into a prototype function and run that by itself since the input values are observable variables inside the object anyway?

**Comment by brianmhunt** [comment] 2015-05-22 11:21
Thanks for the update @LastElf – Yes, the issue would appear to be that  KSB does not support inline `function` statements. 

The underlying reasons are twofold:

1. KSB is not a full Javascript parser, and does not (at least at the moment, and for the second reason below probably will never) include function statements; and

2. The reason KSB exists is to use Knockout with a [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives) (CSP) that prohibits `unsafe-eval` and `unsafe-inline` scripts – so the only scripts that can run are those in separate script files from domains marked safe by the CSP. This is the default, immutable, policy of web apps.

So if you are using KSB you cannot use `function` statements in `data-bind` attributes. Since you are making a web app, there is no way around this without writing a full Javascript interpreter that runs in Javascript (or some other such wild nonsense).

So you are exactly right in thinking that the function needs to go on the `$data` or `$context` objects of Knockout (i.e. the objects you pass to or are constructed by Knockout), and you just reference that function.

Does that help? :grin:

Since this would seem to be an issue you can fix on your end, I will close this – but feel free to keep discussing it, let me know if you have any other issues, or if I have missed something and this is an issue with KSB that we should address.

Thanks and cheers

**Closed by brianmhunt** 2015-05-22 11:21 UTC

**Comment by LastElf** [comment] 2015-05-22 13:13
Yeah that makes enough sense. I should be able to work around it easily enough. After that and I find a configurable timer (I was using jquery.timer) that doesn't use eval I should have finished the port over to being a Chrome app! Then I can actually start work on my save files and doing more content creation.

Sorry to take up your time with something that wasn't really a problem, but you've helped make sense of how things work :) Thanks a lot!

**Comment by brianmhunt** [comment] 2015-05-22 22:38
No worries, glad to help @LastElf
